version: '2.1'

services: 
  osx-alpine-base:
    image: namic:5000/osx-alpine-base
    build: $PWD/osx-alpine-base

  osx-alpine-base-minion:
    build: $PWD/osx-alpine-base-minion
    image: namic:5000/osx-alpine-base-minion
    depends_on:
      - osx-alpine-base-webapp

  osx-alpine-base-webapp:
    build: $PWD/osx-alpine-base-webapp
    image: namic:5000/osx-alpine-base-webapp
    depends_on:
      - osx-alpine-base

  osx-alpine-mojo:
    build: $PWD/osx-alpine-mojo
    image: namic:5000/osx-alpine-mojo
    depends_on:
      - osx-alpine-base
    volumes:
      - $PWD/osx-alpine-mojo/example-app:/example-app
    environment:
      - "PERL5LIB=/example-app"
    ports:
      - "443:443"
    command: hypnotoad -f /example-app/MyApp.pl

            
            
