version: '2.1'

services: 
  osx-alpine-base:
    image: namic:5000/osx-alpine-base
    build: $PWD/osx-alpine-base

  osx-alpine-base-minion:
    build: $PWD/osx-alpine-base-minion
    image: namic:5000/osx-alpine-base-minion
    depends_on:
      - osx-alpine-base-webapp

  osx-alpine-base-webapp:
    build: $PWD/osx-alpine-base-webapp
    image: namic:5000/osx-alpine-base-webapp
    depends_on:
      - osx-alpine-base